misitio/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail')
]

misitio/misitio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

misitio/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

# Create your models here.
class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    
    objects = models.Manager()
    published = PublishManager() 
    
    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title

misitio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.
def post_list(request):
    posts = Post.published.all()

    return render(request,
                  'blog/post/list.html',
                  {'posts': posts})

def post_detail(request, id):
    post = get_object_or_404(Post,
                             id = id,
                             status=Post.Status.PUBLISHED)
    
    return render(request,
                  'blog/post/detail.html',
                  {'post': post})

misitio/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

</head>
<body>

    <div class="columns">
        <div class="column is-two-thirds mt-3 ml-3">
            {% block content %}
            {% endblock%}
        </div>
    </div>
    
</body>
</html>

misitio/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title%} {{ post.title }} {% endblock %}

{% block content %}

    <h1 class="is-size-2">{{ post.title }}</h1>
    <p class="date pb-2 has-text-weight-light is-italic">
        Publicado {{ post.publish }} por {{ post.author }}
    </p>

    {{ post.body | linebreaks }}

{% endblock %}

misitio/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title%} Mi Blog {% endblock %}

{%block content%}

    <h1 class="is-size-1">Mi Blog</h1>

    {% for post in posts %}

        <h2 class="is-size-3">
            <a href="{% url 'blog:post_detail' post.id %}">
                {{post.title}}
            </a>
        </h2>

        <p class="date is-italic has-text-weight-light pb-2">
            Publicado {{ post.publish }} por {{ post.author }}
        </p>

        {{ post.body|truncatewords:30|linebreaks }}

    {% endfor%}

{% endblock%}